<Project>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <WarningsAsErrors>nullable</WarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NeutralLanguage>en</NeutralLanguage>
    <Company>ZixCafe</Company>
    <Product>ZixCafe Pro</Product>
    <Version>0.1.0</Version>
  </PropertyGroup>
</Project>
