<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UserSecretsId>dotnet-ZixCafe.Client.Service-2484ecd7-7acc-45d2-93b4-5b61ec47c084</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZixCafe.Shared\ZixCafe.Shared.csproj" />
  </ItemGroup>

</Project>
